version: "3.1"
services: 
  tomcat:
    image: tomcat:8.0
    volumes:
      - "${TEMP}/usr/local/tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml"
      - "${TEMP}/keys:/root/keys"
    ports:
      - 8080:8080
      - 8443:8443

networks:
  aspnetcoreapp-network:
    driver: bridge